/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 earth.gltf --transform 
Files: earth.gltf [60.52KB] > earth-transformed.glb [119.54KB] (-98%)
Author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
Title: Low Poly Planet Earth
*/

import React, { useContext, useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { APIContext } from "../context/context";

export default function Model(props) {
  const { rotationX } = useContext(APIContext);
  const { nodes, materials } = useGLTF("/earth-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_Planet_0.geometry}
        material={materials.Planet}
        position={[0.2, 0.4, 2.8]}
        rotation={[0.4, -rotationX, -0.1]}
        scale={0.9}
      />
    </group>
  );
}

useGLTF.preload("/earth-transformed.glb");
